name: Acceptance Tests Quality

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: 
        description: "The status of the job"
        value: ${{ job.status }}
    steps:
      - uses: actions/checkout@v2

      - name: x
        run: echo "hello"
      - name: set output
        if: ${{ always() }}
        run: echo ::set-output name=status::$?
 
  unit_test:
    runs-on: ubuntu-latest
    outputs:
      status: 
        description: "The status of the job"
        value: ${{ job.status }}
    needs: check
    steps:
      - uses: actions/checkout@v2
      - name: x2
        run: echo "chao"
      - name: set output
        if: ${{ always() }}
        run: echo ::set-output name=status::$?

  notification:
    runs-on: ubuntu-latest
    needs:
     - check
     - unit_test
    steps:
      - uses: actions/checkout@v2

      - name: Discord success notification
        if: ${{ needs.check.outputs.status }} == 0 && ${{ needs.unit_test.outputs.status }} == 0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Ui test ran successfully <3 :love: :smile: status= ${{ needs.check.outputs.status }}'

      - name: Discord failure notification
        if: ${{ needs.check.outputs.status }} != 0 || ${{ needs.unit_test.outputs.status }} != 0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Ui test failed :warning:'
