name: Acceptance Tests Quality

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: x
        run: echo "hello"
 
  unit_test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - name: x2
        run: echo "chao"

  notification:
    runs-on: ubuntu-latest
    needs:
     - check
     - unit_test
    steps:
      - uses: actions/checkout@v2

      - name: Discord success notification
        if: ${{ needs.check.status }} == 'success' && ${{ needs.unit_test.status }} == 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Ui test ran successfully <3 :love: :smile: status= ${{ needs.check.status }}'

      - name: Discord failure notification
        if: ${{ needs.check.status }} != 'success' || ${{ needs.unit_test.status }} != 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Ui test failed :warning:'
